### ISSUE TITLE
your project as a case study for the Open Reproducible Science sessions?

### ISSUE THREAD

**Issue by ernestguevarra** [grecomalijan/Awareness-Driven-Behaviour#1]
Hi @grecomalijan. Would you be interested in having your research project to be included as a case study for the Open Reproducible Science sessions for this year?

Also, it might be nice for us to showcase your repository within the Oxford IHTM GitHub organisation account. Would you consider possibly cloning your repository to be also available via the Oxford IHTM account?

Finally, would you consider working together on your analysis and output scripts so that we can make it fully reproducible and automatable for use with new data?

**Comment by grecomalijan** [comment]
Hello @ernestguevarra! This sounds great, and I'd be interested to have it included. I have to admit I haven't touched this in ages (as per the logs) but I have used my script in some work-related projects (mostly in data viz). I'll have it cloned via OxIHTM account.  Yes, I'm keen to work on the analysis and output scripts. Happy to discuss this further. 

Very best wishes,
Greco :D

**Comment by ernestguevarra** [comment]
Great! Thanks. This is really helpful so we can have a showcase of reproducible projects that we can show new students. I am working with Giri on his research for his thesis as well.

I think what I propose to do is that we clone/mirror this repository to the `OxfordIHTM` account so that all your commits and changes so far is documented. Then you can keep this copy in your account for your own records (you know you can DOI this and add it as an academic output - more and more in the analytics circles they see output not just as academic papers but code).

Then for the clone, we can work together on it remotely to convert it into a fully reproducible workflow from which you can potentially build on new outputs using new data (or for whatever future usage you think it will be good for). We can automate it and deploy your Shiny app live so there can be a link you can share to others (and on your CV) as your output.

Sorry for messaging you on here. I realise I don't have your non-Oxford email address and I didn't want to bother you with a direct message on a messaging app.

Will be in touch with details on how we will perform the cloning.

**Comment by ernestguevarra** [comment]
hi @grecomalijan, I am reviewing your repository and what I am noting from the commit is that you created this via uploading the entirety of your script with associated files into GitHub. Hence my assumption is that you don't have git setup on your computer and with your RStudio?

If so, I think we might have to decide how best to do the mirroring of the repository as this operation requires a fully setup git and a bit of coding on terminal.

If you want to give it a go, following will be the steps that I think you will first need to do to get setup with git and then the terminal codes you need to run to mirror the repository to the `OxfordIHTM` organisation.

**1. Install and setup git on your computer**

See this guide on how to do this - https://happygitwithr.com/install-git.html.

I think you are using a Mac, so the specific part of that guide for mac is here - https://happygitwithr.com/install-git.html

git is already usually installed on a Mac but it is usually a very old version so it is still recommended to install. Option 1 in the guide is the best way to do this.

After you have installed git, it would be important to do the process described here to make git work properly - https://happygitwithr.com/hello-git.html

**2. Setup git with RStudio**

First you need to setup personal access token with GitHub by following these instructions - https://happygitwithr.com/https-pat.html

Then, you need to connect RStudio with GitHub via git - https://happygitwithr.com/rstudio-git-github.html

Follow these steps using your the GitHub repository for your `Awareness-Driven-Behaviour` repository to obtain a local version of the repository on your computer.

**3. Mirror your local repo to the OxfordIHTM organisation**

Now that you have your repo locally, we can now mirror this into the `OxfordIHTM` organisation. The next steps will now be performed on your terminal. The terminal can be accessed via your RStudio.

If you use the terminal via RStudio within your local repo project, your terminal directory would already be configured for the project directory.

Then enter the following script on terminal to mirror your local repo to the OxfordIHM organisation:

```
git push --mirror https://github.com/OxfordIHTM/Awareness-Driven-Behaviour.git
```

This should now mirror your exact repository into the `OxfordIHTM` organisation account to repository that I already prepositioned on the `OxfordIHTM` account with the same repository name.

Let me know if these steps make sense.

**Comment by ernestguevarra** [comment]
@grecomalijan well done! Thanks for taking the time to work on this as I know you have got far more important things to do than this.

Again, this is helpful to me because I can use your work as a case study for the Open Reproducible Science classes I am teaching.

I will be in touch with you on next steps but please don't feel you have to work on those things right away. We can take our time on those.

I am closing this issue now and will raise the new action points on the repository you created in the OxfordIHTM acount.
